#!/bin/sh

# run from project dir

echo "killing running trackermain process... "
echo "(will fail to kill ps proc)"
proc=linux.catbook
kill $(ps aux | grep $proc | awk '{print $2}') # kill trackermain

pushd $HOME/sland.rotblauer.com;
./$proc -config config.json >> $HOME/sland.rotblauer.com/logs.log 2>&1 &

popd;

